version: "3"
services:

  # zookeeper
  zookeeper:
    platform: linux/amd64
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  # kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    expose:
      - "9092"
      - "29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092, LISTENER_DOCKER_EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT, LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "test"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - kafka-net

  # kafka producer
  kafka-producer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
     - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: LISTENER_DOCKER_INTERNAL://kafka:9092
    networks:
     - kafka-net

  # risingwave
  risingwave:
    image: risingwavelabs/risingwave:v1.6.0
    ports:
    - 5690:5690
    - 5691:5691
    - 4566:4566
    entrypoint:
    - /risingwave/bin/risingwave
    - playground
    networks:
     - kafka-net

  # metabase
  # use host = risingwave
  metabase:
    platform: linux/amd64
    image: metabase/metabase
    ports: 
    - 3000:3000
    networks:
    - kafka-net

networks:
  kafka-net:
    driver: bridge
    name: kafka-net
